postgres:
  image: postgres:9.4.5
  environment:
    POSTGRES_USER: snips
    POSTGRES_PASSWORD: password
  ports:
    - '5432:5432'
  volumes:
    - snips-postgres:/var/lib/postgresql/data

redis:
  image: redis:3.0.5
  ports:
    - '6379:6379'
  volumes:
    - snips-redis:/var/lib/redis/data

snips:
  build: .
  links:
    - postgres
    - redis
  volumes:
    - .:/snips
  ports:
    - '8000:8000'
  env_file:
    - .snips.env

sidekiq:
  build: .
  command: bundle exec sidekiq -C config/sidekiq.yml
  links:
    - postgres
    - redis
  volumes:
    - .:/snips
  env_file:
    - .snips.env
